# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "122033def62ec92564cc4936cb870f44d9e6e8aece152bf72be564b1cac542638c76";
    path = fetchzip {
      url = "https://github.com/karlseguin/zul/archive/e48d01c578b95c1a15957ba819e4094bff982277.tar.gz";
      hash = "sha256-Z4t16dGyO/HVKi/RuTkNyBB8sKHVdkMqxGNGC2tAbq4=";
    };
  }
  {
    name = "122061f30077ef518dd435d397598ab3c45daa3d2c25e6b45383fb94d0bd2c3af1af";
    path = fetchzip {
      url = "https://github.com/karlseguin/metrics.zig/archive/cf2797bcb3aea7e5cdaf4de39c5550c70796e7b1.tar.gz";
      hash = "sha256-9wb9pU3jTXfZYaQzPuW0IrsftJTyRCJfG9oks6RpKy4=";
    };
  }
  {
    name = "1220aab1cba5e34a4d37e59475642e19208e627c9780a5d1c4eab3661994a2872ca0";
    path = fetchzip {
      url = "https://github.com/karlseguin/buffer.zig/archive/e9c95a7719996ce5e1e6a9a6eb3945dda9d98e28.tar.gz";
      hash = "sha256-7DayZEMonUFwm2mkZEjbh24ZDyniZB9finJ3gcwBw20=";
    };
  }
  {
    name = "1220c255f637fecbf185e9f1bac0adc151e599c7666b15911b3227b0cc89c993acdc";
    path = fetchzip {
      url = "https://github.com/karlseguin/pg.zig/archive/ae5ee02b6e4ac9877c4cb340f8251da1f35fc784.tar.gz";
      hash = "sha256-8n+AIwCaA7V3qqnbciIi9JFFabyFHoG6nHSw0PeMnko=";
    };
  }
  {
    name = "jetcommon-0.1.0-jPY_DS1HAAAP8xp5HSWB_ZY7m9JEYUmm8adQFrse0lwB";
    path = fetchzip {
      url = "https://github.com/jetzig-framework/jetcommon/archive/fb4edc13759d87bfcd9b1f5fcefdf93f8c9c62dd.tar.gz";
      hash = "sha256-6at6r0KGzQUPKUb3aHi+vbp8XOOQUbUbTbLWcbEBdvs=";
    };
  }
  {
    name = "jetquery-0.0.0-TNf3zjZWBgCLlUMITutBU9dP72AfSVYobcdYJ4AmJT2H";
    path = fetchzip {
      url = "https://github.com/jetzig-framework/jetquery/archive/6c3fa3c8557d24b8e6a022632909d162e86be5d7.tar.gz";
      hash = "sha256-mb26UjyJ+LxF86A+D9p4IZPBut0JCqHzeVp+0u/58ZI=";
    };
  }
  {
    name = "zig_args-0.0.0-jqtN6P_NAAC97fGpk9hS2K681jkiqPsWP6w3ucb_ctGH";
    path = fetchzip {
      url = "https://github.com/bobf/zig-args/archive/88cbade9a517a4014824f8f53f3c48c8a0b2ffe1.tar.gz";
      hash = "sha256-ntViRk0LcjGD0D7qoPBIhwiBvUSc3+wx/kbUsnropgc=";
    };
  }
]
