# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "122033def62ec92564cc4936cb870f44d9e6e8aece152bf72be564b1cac542638c76";
    path = fetchzip {
      url = "https://github.com/karlseguin/zul/archive/e48d01c578b95c1a15957ba819e4094bff982277.tar.gz";
      hash = "sha256-Z4t16dGyO/HVKi/RuTkNyBB8sKHVdkMqxGNGC2tAbq4=";
    };
  }
  {
    name = "N-V-__8AAAOLAACqscul40pNN-WUdWQuGSCOYnyXgKXRxOqz";
    path = fetchzip {
      url = "https://github.com/karlseguin/buffer.zig/archive/e9c95a7719996ce5e1e6a9a6eb3945dda9d98e28.tar.gz";
      hash = "sha256-7DayZEMonUFwm2mkZEjbh24ZDyniZB9finJ3gcwBw20=";
    };
  }
  {
    name = "N-V-__8AAHOzAQBh8wB371GN1DXTl1mKs8Rdqj0sJea0U4P7";
    path = fetchzip {
      url = "https://github.com/karlseguin/metrics.zig/archive/cf2797bcb3aea7e5cdaf4de39c5550c70796e7b1.tar.gz";
      hash = "sha256-9wb9pU3jTXfZYaQzPuW0IrsftJTyRCJfG9oks6RpKy4=";
    };
  }
  {
    name = "jetcommon-0.1.0-jPY_DS1HAAAP8xp5HSWB_ZY7m9JEYUmm8adQFrse0lwB";
    path = fetchzip {
      url = "https://github.com/jetzig-framework/jetcommon/archive/fb4edc13759d87bfcd9b1f5fcefdf93f8c9c62dd.tar.gz";
      hash = "sha256-6at6r0KGzQUPKUb3aHi+vbp8XOOQUbUbTbLWcbEBdvs=";
    };
  }
  {
    name = "jetquery-0.0.0-TNf3zm-5BgDOtCpRuVLEZQMWjkgKWRe1pNlGhrdoyvYE";
    path = fetchzip {
      url = "https://github.com/jetzig-framework/jetquery/archive/907acae15dd36834dbdab06b17c3ba8f576d77cb.tar.gz";
      hash = "sha256-WJ8Dxoef/pDoM6uUKKNs4ZyKFAXkKwG4ij6oNaahCes=";
    };
  }
  {
    name = "pg-0.0.0-Wp_7gQr-BQAMQ8q9R0TzXrVgsyLVubJpg7mg_CSSIYqI";
    path = fetchzip {
      url = "https://github.com/karlseguin/pg.zig/archive/740b6bfe31bc3ebc81b7bc97fe883871da2604c7.tar.gz";
      hash = "sha256-fLHFvu1kgzMafT7UcN0fjAKuNLjxPRGCCw5Bfw+dNoE=";
    };
  }
  {
    name = "zig_args-0.0.0-jqtN6P_NAAC97fGpk9hS2K681jkiqPsWP6w3ucb_ctGH";
    path = fetchzip {
      url = "https://github.com/bobf/zig-args/archive/88cbade9a517a4014824f8f53f3c48c8a0b2ffe1.tar.gz";
      hash = "sha256-ntViRk0LcjGD0D7qoPBIhwiBvUSc3+wx/kbUsnropgc=";
    };
  }
]
